{% set name = "curio" %}
{% set version = "1.5" %}
{% set sha256 = "af08212e590bb7da8e4cc39c42012711494dc20d622f162155ba296cc2e3bc10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  # Commenting out pytest tests as they were hanging in Azure Pipelines on 2021-03-18.
  # source_files:
  #   - tests
  #   - examples
  # requires:
  #   - pytest
  imports:
    - curio
  # commands:
  #   - pytest

about:
  home: https://curio.readthedocs.org/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: The coroutine concurrency library.
  description: |
    Curio is a library for performing concurrent I/O and common system programming
    tasks such as launching subprocesses and farming work out to thread and process
    pools. It uses Python coroutines and the explicit async/await syntax introduced
    in Python 3.5. Its programming model is based on cooperative multitasking and
    existing programming abstractions such as threads, sockets, files, subprocesses,
    locks, and queues. You'll find it to be small and fast.
  doc_url: https://curio.readthedocs.org/
  dev_url: https://github.com/dabeaz/curio
